language: node_js
node_js:
  - 5.0
services:
  - mongodb
install:
  - npm install -g npm@latest
  - npm install
  - npm install -g gulp
  - npm install -g bower
  - bower install
before_script:
  - mongo dilemmeTest --eval 'db.addUser("dilemme", "dilemme");'
script: gulp test