language: node_js
node_js:
  - 5.0
services:
  - mongodb
install:
  - npm install
  - npm install -g gulp
  - npm install -g bower
  - bower install
before_script:
  - sleep 15
  - mongo dilemmeTest --eval 'db.addUser("dilemme", "dilemme);'
script: gulp test